# Generated by Django 5.0.1 on 2025-02-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_alter_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.CreateModel(
            name='Tentative_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('W', 'Work'), ('L', 'Leisure'), ('E', 'Exercise')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.user')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tentative_task_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='templates.tentative_task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.tentative_task'),
        ),
    ]
